module.exports = {
  components: [
    'dayspicker',
    'range',
    'switch',
    'power',
    'panel',
    'dialog',
    'alert',
    'confirm',
    'button',
    'button-switch',
    'button-group',
    'counter',
    'modes',
    'mask',
    'picker',
    'checkboard',
    'action-sheet',
    'action-box',
    'input',
    'timer',
    'timer-task',
    'timepicker',
    // 'transition', // 引入了整个 animation.css 导致样式文件过大
    'slide',
    'toast',
    'loading',
    'control-center',
    'search',
    'textarea',
    'icon',
  ],
};
